import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../../globals.css";
import { Navbar } from "@/components/Navbar";
import { NextIntlClientProvider } from "next-intl";
import { PriceFilter } from "@/components/PriceFilter";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function Layout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}) {
  const { locale } = await params;

  const messages =
    (await import(`@/messages/${locale}.json`)).default;

  return (
    <html
      lang={locale}
      dir={locale === "ar" ? "rtl" : "ltr"}
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
      suppressHydrationWarning
    >
      <body className="min-h-full flex flex-col">
        <NextIntlClientProvider messages={messages}>
          <Navbar />
          <div className="ctm-container  ">
            <div className="fixed top-27" >
              <PriceFilter />
            </div>
            <div className="w-[calc(100%-350px)] mt-10 pl-4 ml-auto" >
              {children}
            </div>
          </div>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}